modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
description='''
${mod_description}
'''
authors="${mod_authors}"

# 可扩展枚举声明（用于追加自定义 Rarity 稀有度）
enumExtensions = "META-INF/enumextensions.json"

# Mixin 配置声明
[[mixins]]
config="${mod_id}.mixins.json"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="curios"
type="required"
versionRange="[9.0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="taa"
type="required"
versionRange="[1.4.0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="apothic_attributes"
type="required"
versionRange="[2.0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="irons_spellbooks"
type="optional"
versionRange="*"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="jei"
type="optional"
versionRange="*"
ordering="AFTER"
side="CLIENT"
